---
- name: Install shotcut dependencies
  apt:
    name: "{{ item }}"
  with_items:
  - libxcb-shape0
  - libxcb-xfixes0
  - libxslt1.1

- name: Download Shotcut video editor (includes melt)
  get_url:
    # stored on local server for performance
    url: "https://github.com/mltframework/shotcut/releases/download/v17.06/shotcut-linux-x86_64-170601.tar.bz2"
    dest: /tmp

- name: unpack Shotcut video editor (includes melt)
  unarchive:
    src: /tmp/shotcut-linux-x86_64-170102.tar.bz2
    dest: /usr/local/
    copy: no
    creates: /usr/local/Shotcut/Shotcut.desktop

- name: link in ~/bin to melt
  file:
    state: link
    src: /usr/local/Shotcut/Shotcut.app/{{ item }}
    dest: /usr/local/bin/{{ item }}
  with_items:
  - melt
  - shotcut
