---
room_name: room_1

irc_room_channel: "#timvideos"
irc_nick: gator_box

alsa_device: hw:1,0
audio_delay: 1000


blackmagic:
  desktopvideo: http://dc10b/bm/Blackmagic_Desktop_Video_Linux_10.9a7/deb/amd64/desktopvideo_10.9a7_amd64.deb
#   desktopvideo_gui: http://dc10b/bm/Blackmagic_Desktop_Video_Linux_10.9a7/deb/amd64/desktopvideo-gui_10.9a7_amd64.deb
  mediaexpress: http://dc10b/bm/Blackmagic_Desktop_Video_Linux_10.9a7/deb/amd64/mediaexpress_3.5.3a1_amd64.deb
  dkms_version: 10.9a7

blackmagic_sources:
- card: 0
  connection: sdi-audio

sources:
- Cam1
- Grabber1
