---
staticips:
  hosts:
  - hostname: gw
    ip: 10.42.0.1
    mac: f8:d1:11:00:54:38

  - hostname: wifi
    ip: 10.42.0.2
    mac: e4:95:6e:40:2e:d3

  - hostname: blue-mix # Lenovo W530    
    ip: 10.42.0.80
    mac: 3c:97:0e:7f:d9:4c

  - hostname: blue-cam # Lenovo T410
    ip: 10.42.0.81
    mac: f0:de:f1:49:04:a8

  - hostname: magenta-mix # Lenovo W530
    ip: 10.42.0.90
    mac: 3c:97:0e:7f:d8:c0

  - hostname: magenta-cam # Lenovo T410
    ip: 10.42.0.91
    mac: f0:de:f1:49:04:ce

  - hostname: orange-mix # Lenovo W530
    ip: 10.42.0.50
    mac: 3c:97:0e:9d:af:50

  - hostname: orange-cam # Lenovo T410
    ip: 10.42.0.51
    mac: f0:de:f1:49:04:62

  - hostname: red-mix # HP EliteDesk 800
    ip: 10.42.0.10
    mac: 68:05:ca:57:d7:9f 

  - hostname: redspare-mix 
    ip: 10.42.0.10
    mac: 64:00:6a:8a:44:33

  - hostname: red-grab # Lenovo T410
    ip: 10.42.0.11
    mac: f0:de:f1:3e:8d:ae

  - hostname: red-cam2 # Lenovo T410
    ip: 10.42.0.12
    mac: f0:de:f1:49:04:e5

  - hostname: yellow-mix
    ip: 10.42.0.60
    mac: 3c:97:0e:53:ce:07

  - hostname: yellow-cam 
    ip: 10.42.0.61
    mac: f0:de:f1:49:04:e2
 
  - hostname: green-mix # Lenovo T410
    ip: 10.42.0.70
    mac: 3c:97:0e:9d:af:4f

  - hostname: green-cam # Lenovo W530
    ip: 10.42.0.71
    mac: f0:de:f1:49:72:35

  write_hosts: true
  write_interfaces: true
