---
room_name: cockle_bay

irc_room_channel: "#pyconau-c1"
irc_nick: pca-c1
keynote_venue: true

static_ip: 10.42.0.10

sources:
- Camera1
- GrabberL
- GrabberR

blackmagic:
  urls:
    desktopvideo: http://storage/bm/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/desktopvideo_11.2a8_amd64.deb
    desktopvideo_gui: http://storage/bm/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/desktopvideo-gui_11.2a8_amd64.deb
  dkms_version: 11.2a8

blackmagic_sources:
- card: 0
  connection: SDI
  audio: true
  mode: 720p50
